name: edtech_mobile
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  cached_network_image: ^3.2.3
  cloud_firestore: ^4.8.4
  dartz: ^0.10.1
  either_dart: ^1.0.0
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0
  firebase_storage: ^11.2.5
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.0
  flutter_svg: ^2.0.7
  flutter_vector_icons: ^2.0.0
  freezed_annotation: ^2.4.1
  google_sign_in: ^6.1.4
  image_picker: ^1.0.1
  json_annotation: ^4.8.1
  onboarding: ^3.1.0
  relative_time: ^4.0.1
  shared_preferences: ^2.2.0
  stacked: ^3.4.1
  stacked_services: ^1.3.0
  youtube_player_flutter: ^8.1.2
  youtube_player_iframe: ^4.0.4

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  mockito: ^5.4.2
  stacked_generator: ^1.4.0
  freezed: ^2.4.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
  fonts:
    - family: Rubik
      fonts: 
      - asset: assets/fonts/Rubik-Regular.ttf